# Generated by Django 5.2.8 on 2025-11-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_author_alter_blog_options_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='editorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blogs', models.ManyToManyField(related_name='editors', to='Posts.blog')),
            ],
        ),
    ]
